#!/bin/bash 

set -e

# CFYX is a preprocessor to add conveniences to the cfy command

ADDARGS=""
CFYX_HOME=~/.cfyx
CFY=`type -P cfy`

if [ ! -d ~/.cfyx ]; then
  mkdir ~/.cfyx
fi

if [ $# -eq 0 ]; then
  $CFY
  exit $?
fi

if [[ $1 == ex* ]]; then
  if [ "$2" = "start" ]; then
    flag=0
    for arg in $@; do
      if [ "$arg" = "-d" ]; then
        flag=1
      elif [ $flag -eq 1 ]; then 
        dpmt=$arg
        break
      fi
    done

    if [ ! -d $CFYX_HOME/$dpmt ]; then
      mkdir $CFYX_HOME/$dpmt
    fi

    $CFY $*

    echo $dpmt
    exe=`$CFY executions list -d $dpmt | grep '^| [a-z0-9]'|tail -1|cut -f2 -d' '`
    echo $exe > $CFYX_HOME/$dpmt/execution
  else
    $CFY $*
  fi

elif [[ $1 == can* ]]; then
    d=`ls -1rt $CFYX_HOME|tail -1`
    e=`cat $CFYX_HOME/$d/execution`
    $CFY executions cancel $e
elif [[ $1 == uni* ]]; then
  # Handle simple uninstall. If no deployment specified use last
  d=`ls -1rt $CFYX_HOME|tail -1`
  $CFY executions start uninstall -d $d -p ignore_failure=true
elif [[ $1 == cun* ]]; then
  # Handle simple cuninstall (cancel+uninstall). If no deployment specified use last
  d=`ls -1rt $CFYX_HOME|tail -1`
  e=`cat $CFYX_HOME/$d/execution`
  $CFY executions cancel $e
  sleep 4
  $CFY executions start uninstall -d $d -p ignore_failure=true
elif [[ $1 == eli* && $# == 1 ]]; then
  # list executions for last dep
  d=`ls -1rt $CFYX_HOME|tail -1`
  $CFY exec list -d $d
elif [[ $1 == dli* && $# == 1 ]]; then
  $CFY depl list
elif [[ $1 == evli* && $# == 1 ]]; then
  # get events for last execution
  d=`ls -1rt $CFYX_HOME|tail -1`
  e=`cat $CFYX_HOME/$d/execution`
  $CFY eve list -e $e
else
  echo $HERE
  $CFY $*
fi
